src/Entity/ToDo.php
<?php

namespace App\Entity;

use App\Repository\ToDoRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ToDoRepository::class)
 */
class ToDo
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;


    /**
     * @ORM\Column(type="datetime")
     */
    private $create_date;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }





    public function getCreateDate(): ?\DateTimeInterface
    {
        return $this->create_date;
    }

    public function setCreateDate(\DateTimeInterface $create_date): self
    {
        $this->create_date = $create_date;

        return $this;
    }
}

src/Controller/MemberController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Routing\Annotation\Route;

/** @Route("/member") */
class MemberController extends Controller
{

    /**
     * @Route("/")
     */
    public function index()
    {
        return $this->render('member/accueil.html.twig', ['mainNavMember' => true, 'title' => 'PProject5 - Espace Membre']);
    }


    /**
     * @Route("/rss", name="app_project_rss")
     */
    public function rss()
    {
        // url des rss

        $rss = simplexml_load_file('https://www.francetvinfo.fr/france.rss');
        $rss2 = simplexml_load_file('https://www.toolinux.com/spip.php?page=backend');
        $rss3 = simplexml_load_file('https://mrmondialisation.org/feed/');

        return $this->render('member/rss.html.twig', array(
            'rssItems' => $rss->channel->item,
            'rssItems2' => $rss2->channel->item,
            'rssItems3' => $rss3->channel->item,
        ));
    }


    /**
     * @Route("/carte", name="app_project_carte")
     */
    public function carte()
    {
        return $this->render('member/carte.html.twig');
    }

    /**
     * @Route("/mail", name="app_project_mail")
     */
    public function mail()
    {
        return $this->render('member/mail.html.twig');
    }


    /**
     * @Route("/calendrier", name="app_project_calendrier")
     */
    public function calendrier()
    {
        return $this->render('member/calendrier.html.twig');
    }


    /**
     * @Route("/accueil", name="app_project_accueil")
     */
    public function accueil()
    {
        return $this->render('member/accueil.html.twig');
    }
}

templates/member/accueil.html.twig
{# templates/homepage/index2.html.twig #}
{% extends 'base2.html.twig' %}

{% block title %}PProject5 - Votre portail web personnel
{% endblock %}

{% block content %}

	<div id="container">
		<div class="row">

			<div class="col-12 title">
				<p>
					<h2>Bienvenue sur votre portail web personnel</h2>
				</p>
				<p></p>
			</div>

			<div class="col-sm">
				<div class="card">
					<div class="card-header">
						<svg width="1em" height="1em" viewbox="0 0 16 16" class="bi bi-clock-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
							<path fill-rule="evenodd" d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8 3.5a.5.5 0 0 0-1 0V9a.5.5 0 0 0 .252.434l3.5 2a.5.5 0 0 0 .496-.868L8 8.71V3.5z"/>
						</svg>
						Date | Heure
					</div>
					<div class="card-body">
						<div id="dateJ"></div>
					</div>
				</div>
			</div>

			<div class="col-sm">
				<div class="card">
					<div class="card-header">
						<svg width="1em" height="1em" viewbox="0 0 16 16" class="bi bi-brightness-alt-high-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
							<path fill-rule="evenodd" d="M4 11a4 4 0 1 1 8 0 .5.5 0 0 1-.5.5h-7A.5.5 0 0 1 4 11zm4-8a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 3zm8 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 11a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.414a.5.5 0 1 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zM4.464 7.464a.5.5 0 0 1-.707 0L2.343 6.05a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707z"/>
						</svg>
						Météo
					</div>
					<div class="card-body">
						<div id="weather"></div>
					</div>
				</div>
			</div>

		</div>
	</div>


{% endblock %}

{% block script %}
	<script src="{{ asset('assets/js/date.js')}}"></script>
	<script src="{{ asset('assets/js/weather.js')}}"></script>
{% endblock %}

templates/member/admin.html.twig
{# templates/admin/admin.html.twig #}
{% extends 'base2.html.twig' %}

{% block title %}PProject5 - Administration
{% endblock %}

{% block content %}

	<div id="container">
		<div class="row">

			<div class="col-sm-6">
				<div class="card">
					<div class="card-header">
						<svg width="1em" height="1em" viewbox="0 0 16 16" class="bi bi-info-square-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
							<path fill-rule="evenodd" d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm8.93 4.588l-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM8 5.5a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
						</svg>
						Informations serveur
					</div>
					<div class="card-body">
						<ul>
							<li>Nom d'hôte :
								{{ name }}</li>
							<li>Version de PHP :
								{{ version }}</li>
							<li>Protocol :
								{{ proto }}</li>
							<li>Racine :
								{{ root }}</li>
							<li>Adresse IP :
								{{ ipS }}</li>
						</ul>
					</div>
				</div>
			</div>


			<div class="col-sm-6">
				<div class="card">
					<div class="card-header">
						<svg width="1em" height="1em" viewbox="0 0 16 16" class="bi bi-file-person-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
							<path fill-rule="evenodd" d="M2 3a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V3zm6 7a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm5 2.755C12.146 11.825 10.623 11 8 11s-4.146.826-5 1.755V13a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-.245z"/>
						</svg>
						Informations visiteur
					</div>
					<div class="card-body">
						{% set user = app.user %}
						<ul>
							<li>Utilisateur :
								{{ app.user.email }}</li>
							<li>Identifiant :
								{{ app.user.id }}</li>
							<li>Adresse IP :
								{{ ip }}</li>
							<li>Navigateur :
								{{ nav }}</li>
						</ul>
					</div>
				</div>
			</div>

		</div>
	</div>

{% endblock %}

templates/member/calendrier.html.twig
{# templates/member/calendrier.html.twig #}
{% extends 'base2.html.twig' %}
{% block calendar %}
	<link rel='stylesheet' href="{{ asset('assets/css/fullcalendar.css')}}"/>
	<script src="{{ asset('assets/js/moment.js')}}"></script>
	<script src="{{ asset('assets/js/fullcalendar.js')}}"></script>
	<script src="{{ asset('assets/js/fr.js')}}"></script>
{% endblock %}
{% block title %}PProject5 - Calendrier
{% endblock %}
{% block scriptC %}
	<script type="text/javascript">
		$(function () {
$('#calendar').fullCalendar({
columnHeaderFormat: 'dddd',
weekNumbers: 'true',
locale: 'fr',
navLinks: 'true',
dayClick: function (date, jsEvent, view) {
alert('Date sélectionnée : ' + date.format());
$(this).css('background-color', '#409fe2');
}
})
});
	</script>
{% endblock %}


{% block content %}

	<div id="container">
		<div class="row">

			<div class="col-sm">
				<div class="card">
					<div class="card-header">
						<svg width="1em" height="1em" viewbox="0 0 16 16" class="bi bi-calendar3-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
							<path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2H0z"/>
							<path fill-rule="evenodd" d="M0 3h16v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3zm6.5 4a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm4-1a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm2 1a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm-8 2a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm2 1a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm4-1a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm2 1a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm-8 2a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm2 1a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm4-1a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
						</svg>
						Calendrier
					</div>
					<div class="card-body">
						<div id='calendar'></div>
					</div>
				</div>
			</div>

		</div>
	</div>
{% endblock %}

templates/member/carte.html.twig
{# templates/member/carte.html.twig #}
{% extends 'base2.html.twig' %}
{% block title %}PProject5 - Carte
{% endblock %}

{% block content %}

	<div id="container">
		<div class="row">

			<div class="col-sm">
				<div class="card">
					<div class="card-header">
						<svg width="1em" height="1em" viewbox="0 0 16 16" class="bi bi-geo-alt" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
							<path fill-rule="evenodd" d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
						</svg>
						Carte
					</div>
					<div class="card-body2">

						<div id="carteT">
							<iframe width="100%" height="300px" frameborder="0" allowfullscreen src="//umap.openstreetmap.fr/fr/map/france_490940?scaleControl=false&miniMap=false&scrollWheelZoom=false&zoomControl=true&allowEdit=false&moreControl=true&searchControl=null&tilelayersControl=null&embedControl=null&datalayersControl=true&onLoadPanel=undefined&captionBar=false"></iframe>
							<p>
								<a href="//umap.openstreetmap.fr/fr/map/france_490940">Voir en plein écran</a>
							</p>
						</div>

					</div>

				</div>
			</div>

		</div>
	</div>

{% endblock %}


{% block script %}
{% endblock %}

templates/member/mail.html.twig
{# templates/member/mail.html.twig #}
{% extends 'base2.html.twig' %}

{% block title %}PProject5 - Mail
{% endblock %}

{% block content %}

	<div id="container">
		<div class="row">

			<div class="col-sm">
				<div class="card">
					<div class="card-header">
						<svg width="1em" height="1em" viewbox="0 0 16 16" class="bi bi-envelope-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
							<path fill-rule="evenodd" d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414.05 3.555zM0 4.697v7.104l5.803-3.558L0 4.697zM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586l-1.239-.757zm3.436-.586L16 11.801V4.697l-5.803 3.546z"/>
						</svg>
						Email
					</div>
					<div class="card-body">
						{{ form_start(our_form) }}
						{{ form_widget(our_form) }}

						<input type="submit" value="Send" class="btn btn-success"/>

						{{ form_end(our_form) }}
					</div>
				</div>
			</div>

		</div>
	</div>


{% endblock %}

templates/member/rss.html.twig
{# templates/member/rss.html.twig #}
{% extends 'base2.html.twig' %}
{% block title %}PProject5 - RSS
{% endblock %}

{% block content %}
	<div id="container">
		<div class="row">

			<div class="col-sm">
				<div class="card">
					<div class="card-header">
						<svg width="1em" height="1em" viewbox="0 0 16 16" class="bi bi-rss-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
							<path fill-rule="evenodd" d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm1.5 2.5a1 1 0 0 0 0 2 8 8 0 0 1 8 8 1 1 0 1 0 2 0c0-5.523-4.477-10-10-10zm0 4a1 1 0 0 0 0 2 4 4 0 0 1 4 4 1 1 0 1 0 2 0 6 6 0 0 0-6-6zm.5 7a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3z"/>
						</svg>
						RSS
					</div>
					<div class="card-body">
						<ul>
							{% for item in rssItems|slice(0, 3) %}
								<li>
									<h4>
										<span class='badge badge-secondary'>Titre :
										</span>
									</h4>
									<a href="{{ item.link }}">
										{{ item.title }}</a>
								</li>
								<li>
									{{ item.description|raw }}</li>
							{% endfor %}
						</ul>
					</div>
				</div>
			</div>


			<div class="col-sm">
				<div class="card">
					<div class="card-header">
						<i class="fas fa-rss-square"></i>
						RSS
					</div>
					<div class="card-body">
						<ul>
							{% for item in rssItems2|slice(0, 3) %}
								<li>
									<h4>
										<span class='badge badge-secondary'>Titre :
										</span>
									</h4>
									<a href="{{ item.link }}">
										{{ item.title }}</a>
								</li>
								<li>
									{{ item.description|raw }}</li>
							{% endfor %}
						</ul>
					</div>
				</div>
			</div>


			<div class="col-sm">
				<div class="card">
					<div class="card-header">
						<i class="fas fa-rss-square"></i>
						RSS
					</div>
					<div class="card-body">
						<ul>
							{% for item in rssItems3|slice(0, 3) %}
								<li>
									<h4>
										<span class='badge badge-secondary'>Titre :
										</span>
									</h4>
									<a href="{{ item.link }}">
										{{ item.title }}</a>
								</li>
								<li>
									{{ item.description|raw }}</li>
							{% endfor %}
						</ul>
					</div>
				</div>
			</div>

		</div>
	</div>

{% endblock %}

templates/member/todo.html.twig
{# templates/member/todo.html.twig #}
{% extends 'base2.html.twig' %}

{% block title %}PProject5 - Tâches
{% endblock %}
{% block body %}
	{% block content %}

		<h3>Ajouter une tâche</h3>

		<div class="simpleform">
			{{form(form)}}
			</div>

			<div class="col-sm">
				<div class="card">
					<div class="card-header">
						<svg width="1em" height="1em" viewbox="0 0 16 16" class="bi bi-list-task" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
							<path fill-rule="evenodd" d="M2 2.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5V3a.5.5 0 0 0-.5-.5H2zM3 3H2v1h1V3z"/>
							<path d="M5 3.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM5.5 7a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 4a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9z"/>
							<path fill-rule="evenodd" d="M1.5 7a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5H2a.5.5 0 0 1-.5-.5V7zM2 7h1v1H2V7zm0 3.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5H2zm1 .5H2v1h1v-1z"/>
						</svg>
						Tâches en cours
					</div>

					<div class="card-body">
						<table class="table" table-bordered>
							<thead>
								<tr>
									<th>ID</th>
									<th>Tâche</th>
									<th>Date</th>
									<th>Supprimer</th>
								</tr>
							</thead>
							<tbody>
								{% for afaire in afaires %}
									<tr>
										<td scope="row">{{afaire.id}}</td>
										<td>{{afaire.name}}</td>
										<td>{{afaire.createDate | date('d/m/Y')}}</td>
										<td>
											<a href=/member/todo/delete/ {{afaire.id}}>
												<button type="button" class="btn btn-danger">Supprimer</button>
											</a>

										</td>
									</tr>
								{% endfor %}
							</tbody>
						</table>

					</div>
				</div>
			</div>

		{% endblock %}
	{% endblock %}

templates/member/upload.html.twig
{# templates/member/upload.html.twig #}
{% extends 'base2.html.twig' %}
{% block title %}PProject5 - Fichiers
{% endblock %}
{% block body %}
	{% block content %}
		<h3>Envoi de fichiers</h3>
		<div class="simpleform">
			{{ form_start(form) }}
			{{ form_widget(form) }}
			{{ form_end(form) }}
		</div>


		<div class="col-sm">
			<div class="card">
				<div class="card-header">
					<svg width="1em" height="1em" viewbox="0 0 16 16" class="bi bi-file-arrow-up-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
						<path fill-rule="evenodd" d="M12 15H4a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2zm-3.5-3.5a.5.5 0 0 1-1 0V5.707L5.354 7.854a.5.5 0 1 1-.708-.708l3-3a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708L8.5 5.707V11.5z"/>
					</svg>
					Nombre de fichiers :
					<span class="couleur">{{ filecount }}</span>
					Taille du répertoire :
					<span class="couleur">{{ sizeF }}</span>
					Mo
				</div>
				<div class="card-body">

					<ul>
						{% for filename in filenames %}
							<li>
								<a href=" {{ filename }} " download=" {{ filename }} ">
									{{ filename }}
								</a>
								||
								<a href="{{ path('app_project_upload_delete', {'fichier': filename}) }}">
									<svg width="1em" height="1em" viewbox="0 0 16 16" class="bi bi-trash-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
										<path fill-rule="evenodd" d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5a.5.5 0 0 0-1 0v7a.5.5 0 0 0 1 0v-7z"/>
									</svg>
								</a>
							</li>
						{% endfor %}
					</ul>


				</div>
			</div>
		</div>

	{% endblock %}
{% endblock %}